---
- name: Définir ou modifier le mot de passe de l'utilisateur pierre
  hosts: all
  become: true
  vars:
    my_password: "MotDePasseSécuriséIci"
  tasks:
    - name: Mettre à jour le mot de passe de pierre
      ansible.builtin.user:
        name: pierre
        password: "{{ my_password | password_hash('sha512') }}"
