---
- name: Copier un fichier vers les machines clientes
  hosts: all
  become: true

  vars_files:
    - /root/projet/vars/copie_vars.yaml

  tasks:
  - name: Copie du fichier
    ansible.builtin.copy:
      src: "{{ fichier_source }}"
      dest: "{{ fichier_destination }}"
      owner: "{{ proprietaire }}"
      group: "{{ groupe }}"
      mode: "{{ permissions }}"

