---
- name: Copier sdv.conf vers les clients
  hosts: all
  gather_facts: no

  tasks:
    - name: Copier le fichier sdv.conf dans /tmp des clients
      ansible.builtin.copy:
        src: /root/sdv.conf
        dest: /tmp/sdv.conf
        owner: root
        group: root
        mode: '0644'
