---
- name: Modifier les permissions du fichier /root/vinci
  hosts: ubuntu
  become: true

  tasks:
    - name: S'assurer que le fichier existe
      file:
        path: /root/vinci
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Ajouter les droits d'écriture à tous les utilisateurs
      file:
        path: /root/vinci
        mode: '0666'
