- name: Installer Apache2 sur localhost
  hosts: localhost
  become: true
  tasks:
    - name: Installer le paquet apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Démarrer le service apache2
      service:
        name: apache2
        state: started
        enabled: yes

